apiVersion: v1
kind: Service
metadata:
  name: capi-kubeadm-control-plane-controller-manager-metrics-service
  namespace: capi-kubeadm-control-plane-system
spec:
  ports:
  - name: https
    port: 9848
    targetPort: https
  - $patch: replace
