apiVersion: apps/v1
kind: Deployment
metadata:
  name: capi-kubeadm-bootstrap-controller-manager
  namespace: capi-kubeadm-bootstrap-system
spec:
  template:
    metadata:
      labels:
        name: capi-kubeadm-bootstrap-controller-manager
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: name
                operator: In
                values:
                - capi-kubeadm-bootstrap-controller-manager
            topologyKey: "kubernetes.io/hostname"
