apiVersion: v1
kind: Service
metadata:
  name: capi-controller-manager-metrics-service
  namespace: capi-system
spec:
  ports:
  - name: https
    port: 9844
    targetPort: https
  - $patch: replace
