apiVersion: apps/v1
kind: Deployment
metadata:
  name: capi-controller-manager
  namespace: capi-webhook-system
spec:
  template:
    metadata:
      labels:
        name: capi-webhook
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: name
                operator: In
                values:
                - capi-webhook
            topologyKey: "kubernetes.io/hostname"
