apiVersion: v1
kind: LimitRange
metadata:
  name: default-limit-range
  namespace: cert-manager
spec:
  limits:
  - default:
      cpu: 250m
      memory: 200Mi
    defaultRequest:
      cpu: 25m
      memory: 75Mi
    type: Container
